<div>
<img src="https://drive.google.com/uc?export=view&id=1vK33e_EqaHgBHcbRV_m38hx6IkG0blK_" width="350"/>
</div> 

#**Artificial Intelligence - MSc**
CS6501 - MACHINE LEARNING AND APPLICATIONS
#**Business Analytics - MSc**
ET5003 - MACHINE LEARNING APPLICATIONS 
##***Annual Repeat***
###Instructor: Enrique Naredo

###RepMLA_Lab-1.4

Student ID: 

Student name: 

# Numpy


This part focuses on Numpy, see <a href="http://cs.haverford.edu/faculty/smathieson/teaching/f19/labs/lab01/lab01.html">numpy quickstart tutorial</a>, which I encourage you to reference throughout the course.


Some problems about numpy



# Problem 1 

Create a null vector of size 10 (that is a vector that includes 10 zeros) and print it

In [1]:
#solution
import numpy as np
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Problem 2
Create a null vector of size 10 but the fifth value which is 1 

In [2]:
Z=np.zeros(10)
Z[5]=1
Z

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

# Problem 3
Create a vector with all integer values ranging from 10 to 49 

In [5]:
Z=np.arange(10, 50, 1)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# Problem 4
 Create a 3x3 matrix with values ranging from 0 to 8 

In [6]:
Z=np.arange(0, 9, 1).reshape(3, 3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Problem 5
Create a 3x3x3 array with random values (you can use ` np.random.random`)

In [7]:
Z=np.random.random((3, 3, 3))
Z

array([[[0.03049293, 0.85745671, 0.75209703],
        [0.46066114, 0.6584191 , 0.71271784],
        [0.5311984 , 0.93859507, 0.32794467]],

       [[0.0858897 , 0.42163653, 0.56996451],
        [0.80150982, 0.38051169, 0.31261203],
        [0.98918976, 0.7093103 , 0.73075515]],

       [[0.15765062, 0.63132138, 0.9161105 ],
        [0.2491433 , 0.56856094, 0.00416834],
        [0.63828948, 0.77940308, 0.87250028]]])